# Generated by Django 5.1 on 2024-09-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.TextField(
                default="안녕하세요. 반가워요!",
                max_length=100,
                verbose_name="Profile Description",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                default="static/image/default_profile.png", upload_to="profile/%Y/%m"
            ),
        ),
    ]
