# Generated by Django 5.1 on 2024-09-20 14:08

import customauth.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customauth", "0002_alter_profile_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=customauth.fields.ThumbnailImageField(
                default="static/image/default_profile.png", upload_to="profile/%Y/%m"
            ),
        ),
    ]
