# Generated by Django 5.1 on 2024-10-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customauth", "0004_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="subscriber",
            unique_together={("current_user", "following")},
        ),
    ]
