# Generated by Django 5.1 on 2024-09-15 01:22

import django.db.models.deletion
import photo.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Category name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GifArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="GIF Name")),
                ("gif_image", photo.fields.ThumbnailGifField(upload_to="photo/%Y/%m")),
                ("like", models.PositiveIntegerField(default=0)),
                ("create_dt", models.DateField(auto_now_add=True)),
                ("modify_dt", models.DateField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="photo.category"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OWNER",
                    ),
                ),
            ],
            options={
                "ordering": ("-modify_dt",),
            },
        ),
    ]
