# Generated by Django 5.1 on 2024-09-23 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gifarchive",
            name="like",
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="photo.gifarchive",
                        verbose_name="gif_image",
                    ),
                ),
                (
                    "liker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="liker",
                    ),
                ),
            ],
            options={
                "unique_together": {("liker", "gif")},
            },
        ),
    ]
